#!/usr/bin/env python3
import skilstak.colors as c
import random as r
import sys


with open('./words.txt') as infile:
    words = [line.strip().split(',') for line in infile]

if len(sys.argv) == 2:
    amount = sys.argv[1]
else:
    print(c.green + 'Welcome to the password generator, using random words!')
    print(c.green + 'How many words do you want your password to be?')
    amount = input(c.red + '> ' + c.cyan)

try:
    for count in range(int(amount)):
        print(c.green)
        passwd = r.choice(words)
        print(passwd,end=' ')
    print('\n')
except ValueError:
    print(c.red + 'Please enter an integer!')
